/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** 
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually


  oldSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['authsystem'],
    },
    {
      type: 'category',
      label: 'Add Ons',
      items: ['integrations-overview', 'branch','dlocal','facebookapp','firebase', 'ga','moengage' ,'karix','twilio','google-maps'],
    },
    
    {
      type: 'category',
      label: 'Add Ons',
      items: ['integrations-overview', 'branch','dlocal','facebookapp','firebase', 'ga','moengage' ,'karix','twilio','google-maps'],
    },
  ],
  
};
*/

module.exports = {
  mySidebar: {
    Introduction: ['introduction','overview', 'tradlyecosystem', 'commerce-definitions','support','FAQ' ],
    Setup: ['checklist','deployment','appcustomisation','testingapp','domain','appstore','playstore','website','email','pushnotification'],
    Blocks: ['accounts','authsystem','banners','collection','currency','chat','deeplink','delivery','feed','language','listings','location','notification','order','paymentgateways','revenuemodel','review-ratings','search','subscription','other-blocks'],
    'Integrations': ['integrations-overview', 'stripe-onboarding','stripe', 'branch','dlocal','facebookapp','firebase', 'ga','moengage' ,'karix','twilio','google-maps'],
    'Solution Guide': ['education', 'energy', 'food', 'othersolutions'],
    Changelog: ['changelog-api','changelog-ios','changelog-android'],
    Contribute: ['contribute'],
    'Marketing Features': [],
    'Depreciated Docs': ['superadmin', 'superadmin-guide','appfeatures','webfeatures'],
    TradlyAPI: [],
    Partners: []
  },
};



